-- FILE: 02_vector_magnitude_hardware.sql
-- DATE: 2026-04-16
-- DESCRIPTION: Integrates TSMC CapEx magnitude and North Asia semi-node performance.

SET PAGESIZE 50
SET LINESIZE 150
COLUMN ENTITY FORMAT A25
COLUMN STATUS FORMAT A25

SELECT 
    'TSMC 2026 CAPEX' AS ENTITY, 
    56000.00 AS SPOT, 
    'MAGNITUDE PUSH' AS STATUS 
FROM DUAL
UNION ALL
SELECT 
    'SK HYNIX', 
    1157000.00, 
    'ALPHA LEADER' 
FROM DUAL
UNION ALL
SELECT 
    'SAMSUNG ELECTRONICS', 
    219000.00, 
    'WINNER' 
FROM DUAL
UNION ALL
SELECT 
    'TSMC ADR', 
    363.35, 
    'MEAN REVERSION TARGET' 
FROM DUAL;

COMMIT;
