-- FILE: 07_bank_tech_expenditure_impact.sql
-- DATE: 2026-04-16
-- DESCRIPTION: Correlating $12B Tech Spend with $103B NII Guidance and IBM Breakout.

SET DEFINE OFF;
SET PAGESIZE 50;
SET LINESIZE 150;

COLUMN METRIC FORMAT A20;
COLUMN STATUS FORMAT A20;
COLUMN CATALYST FORMAT A25;

-- 1. TECHNOLOGY CAPEX MAGNITUDE (THE JPM $12B ENGINE)
SELECT 'JPM_TECH_SPEND' AS METRIC, 12.00 AS VAL_B, 'DOMINANT_MOAT' AS STATUS FROM DUAL
UNION ALL
SELECT 'CITI_TECH_SPEND', 9.50, 'LEGACY_TRANSITION' FROM DUAL
UNION ALL
SELECT 'BOFA_TECH_SPEND', 6.00, 'STABLE' FROM DUAL;

-- 2. REVENUE EFFICIENCY & EQUITY NODES
SELECT 'JPM_NII_GUIDE' AS METRIC, 103.00 AS VAL_B, 'TECH_DRIVEN_ALPHA' AS STATUS FROM DUAL
UNION ALL
SELECT 'IBM_EQUITY_NODE', 251.00, 'SOVEREIGN_AI_PIVOT' FROM DUAL;

COMMIT;
